/*
* generated by Xtext
*/
package org.ow2.mindEd.ui.labeling;

import org.ow2.mindEd.itf.ConstantDefinition;
import org.ow2.mindEd.itf.EnumDefinition;
import org.ow2.mindEd.itf.EnumReference;
import org.ow2.mindEd.itf.IncludeDirective;
import org.ow2.mindEd.itf.InterfaceDefinition;
import org.ow2.mindEd.itf.ItfFile;
import org.ow2.mindEd.itf.MethodDefinition;
import org.ow2.mindEd.itf.StructOrUnionDefinition;
import org.ow2.mindEd.itf.TypeDefinition;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
public class ItfLabelProvider extends org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider {

	@Inject
	public ItfLabelProvider(org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	// Labels and icons can be computed like this:
	
	public String image(MethodDefinition obj) {
		// Reuse Image from jdt
		// return org.eclipse.jdt.ui.ISharedImages.IMG_OBJS_PUBLIC;
		return "methpub_obj.gif";

	};

	public String image(EnumReference obj) {
		return "enum_obj.gif";
	};

	public String image(EnumDefinition obj) {
		return "enum_obj.gif";
	};

	public String text(MethodDefinition obj) {
		return "Method " + obj.getName();
	};

	public String image(ItfFile obj) {
		return "InterfaceDefinition.gif";
	}

	public String image(InterfaceDefinition obj) {
		return "int_obj.gif";
	}

	public String image(StructOrUnionDefinition obj) {
		if (obj.getStruct().equals("union"))
			return "union_obj.gif";
		else
			return "struct_obj.gif";
	}

	public String image(TypeDefinition obj) {
		return "typedef_obj.gif";
	}
	
	public String image(ConstantDefinition obj) {
		return "define_obj.gif";

	}
	
	public String image(IncludeDirective obj) {
		return "imp_obj.gif";

	}
}
