/**
 * generated by Xtext
 */
package org.ow2.mindEd.itf.editor.textual.validation;

import org.ow2.mindEd.itf.editor.textual.validation.AbstractFractalItfValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class FractalItfValidator extends AbstractFractalItfValidator {
}
