/*
 * generated by Xtext
 */
package org.ow2.mindEd;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IdtRuntimeModule extends org.ow2.mindEd.AbstractIdtRuntimeModule {

}
