/*
* generated by Xtext
*/
package org.ow2.mindEd;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class IdtStandaloneSetup extends IdtStandaloneSetupGenerated{

	public static void doSetup() {
		new IdtStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

