/*
 * generated by Xtext
 */
package org.ow2.mindEd;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AdlUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.ow2.mindEd.ui.internal.AdlActivator.getInstance().getInjector("org.ow2.mindEd.Adl");
	}
	
}
