/*
 * generated by Xtext
 */
package org.ow2.mindEd.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractItfValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.ow2.mindEd.itf.ItfPackage.eINSTANCE);
		return result;
	}
}
