/*
 * generated by Xtext
 */
package org.ow2.mindEd;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AdlRuntimeModule extends org.ow2.mindEd.AbstractAdlRuntimeModule {

	@Override
	public void configureIScopeProviderDelegate(com.google.inject.Binder binder) {
		binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class).annotatedWith(com.google.inject.name.Names.named(org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.NAMED_DELEGATE)).to(org.ow2.mindEd.scoping.AdlImportedNamespaceAwareLocalScopeProvider.class);
	}
	
}
