/*
 * generated by Xtext
 */
package org.ow2.mindEd.adl.ui.contentassist

import org.ow2.mindEd.adl.ui.contentassist.AbstractAdlProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class AdlProposalProvider extends AbstractAdlProposalProvider {
}
