/*
 * generated by Xtext
 */
package org.ow2.mindEd.adl.ui.contentassist

import org.ow2.mindEd.adl.ui.contentassist.AbstractFractalProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class FractalProposalProvider extends AbstractFractalProposalProvider {
}
