/*
 * generated by Xtext
 */
package org.ow2.mindEd.ui.contentassist

import org.ow2.mindEd.ui.contentassist.AbstractIdtProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class IdtProposalProvider extends AbstractIdtProposalProvider {
}
