/**
 * generated by Xtext
 */
package org.ow2.mindEd.ui.contentassist;

import org.ow2.mindEd.ui.contentassist.AbstractItfProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ItfProposalProvider extends AbstractItfProposalProvider {
}
