/*
 * generated by Xtext
 */
package org.ow2.mindEd;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ItfRuntimeModule extends org.ow2.mindEd.AbstractItfRuntimeModule {

	public Class<? extends org.ow2.mindEd.validation.ItfValidator> bindItfValidator() {
		return org.ow2.mindEd.validation.ItfValidator.class;
	}
	
}
