/*
* generated by Xtext
*/
package org.ow2.mindEd;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ItfStandaloneSetup extends ItfStandaloneSetupGenerated{

	public static void doSetup() {
		new ItfStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

