/**
 * generated by Xtext
 */
package org.ow2.mindEd.validation;

import org.ow2.mindEd.validation.AbstractIdtValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class IdtValidator extends AbstractIdtValidator {
}
