/*
 * generated by Xtext
 */
package org.ow2.mindEd.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.ow2.mindEd.ui.internal.AdlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AdlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AdlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AdlActivator.getInstance().getInjector(AdlActivator.ORG_OW2_MINDED_ADL);
	}
	
}
