/*
* generated by Xtext
*/
package org.ow2.mindEd;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class IdtUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.ow2.mindEd.ui.internal.IdtActivator.getInstance().getInjector("org.ow2.mindEd.Idt");
	}
	
}
