/*
 * generated by Xtext
 */
package org.ow2.mindEd.adl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AdlUiModule extends org.ow2.mindEd.adl.ui.AbstractAdlUiModule {
	public AdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
