/*
 * generated by Xtext
 */
package org.ow2.mindEd.adl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FractalUiModule extends org.ow2.mindEd.adl.ui.AbstractFractalUiModule {
	public FractalUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
