/*
 * generated by Xtext
 */
package org.ow2.mindEd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.ow2.mindEd.ui.highlighting.AntlrTokenToAttributeIdMapper;
import org.ow2.mindEd.ui.highlighting.LexicalHighlightingConfiguration;
import org.ow2.mindEd.ui.resource.ItfResourceUIServiceProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ItfUiModule extends org.ow2.mindEd.ui.AbstractItfUiModule {
	public ItfUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	/**
	 * register syntax coloring
	 * 
	 * @return class which define MIND ITF syntax coloring
	 */
	public Class<? extends IHighlightingConfiguration> bindILexicalHighlightingConfiguration() {
		return LexicalHighlightingConfiguration.class;
	}

	/**
	 * register mapping tokens to IDs
	 * 
	 * @return MIND ITF tokens mapping
	 */
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindTokenToAttributeIdMapper() {
		return AntlrTokenToAttributeIdMapper.class;
	}
	
	public Class<? extends org.eclipse.xtext.ui.resource.IResourceUIServiceProvider> bindResourceUIServiceProvider() {
		return ItfResourceUIServiceProvider.class;
	}
}
