/*
 * generated by Xtext
 */
package org.ow2.mindEd.ui.quickfix;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.model.edit.ISemanticModification;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import org.ow2.mindEd.itf.impl.InterfaceDefinitionImpl;
import org.ow2.mindEd.validation.ItfValidator;

/**
 * Custom quickfixes.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
public class ItfQuickfixProvider extends org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider {

	@Fix(ItfValidator.WRONG_NAME)
	public void renameInterface(final Issue issue,
			IssueResolutionAcceptor acceptor) {

		acceptor.accept(
				issue, 
				"Rename", 
				"Change interface name", 
				null, 
				new ISemanticModification() {

					@Override
					public void apply(EObject element,
							IModificationContext context) throws Exception {
						if (element instanceof InterfaceDefinitionImpl) {

							InterfaceDefinitionImpl interfaceDefinitionImpl = (InterfaceDefinitionImpl) element;							
							String expectedName = ItfValidator.getExpectedInterfaceName(interfaceDefinitionImpl);							
							interfaceDefinitionImpl.setName(expectedName);
						}

					}
				});
	}

}
