/*
* generated by Xtext
*/
package org.ow2.mindEd.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.ow2.mindEd.services.IdtGrammarAccess;

public class IdtParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private IdtGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.ow2.mindEd.parser.antlr.internal.InternalIdtParser createParser(XtextTokenStream stream) {
		return new org.ow2.mindEd.parser.antlr.internal.InternalIdtParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "IdtFile";
	}
	
	public IdtGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(IdtGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
