/*
* generated by Xtext
*/
package org.ow2.mindEd.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.ow2.mindEd.services.IdtGrammarAccess;

public class IdtParser extends AbstractContentAssistParser {
	
	@Inject
	private IdtGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.ow2.mindEd.ui.contentassist.antlr.internal.InternalIdtParser createParser() {
		org.ow2.mindEd.ui.contentassist.antlr.internal.InternalIdtParser result = new org.ow2.mindEd.ui.contentassist.antlr.internal.InternalIdtParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getIdtFileAccess().getAlternatives_3(), "rule__IdtFile__Alternatives_3");
					put(grammarAccess.getIdtFileAccess().getGroup(), "rule__IdtFile__Group__0");
					put(grammarAccess.getConstantDefinitionBeginAccess().getGroup(), "rule__ConstantDefinitionBegin__Group__0");
					put(grammarAccess.getIdtFileAccess().getBegindefAssignment_0(), "rule__IdtFile__BegindefAssignment_0");
					put(grammarAccess.getIdtFileAccess().getDefAssignment_1(), "rule__IdtFile__DefAssignment_1");
					put(grammarAccess.getIdtFileAccess().getIncludesAssignment_2(), "rule__IdtFile__IncludesAssignment_2");
					put(grammarAccess.getIdtFileAccess().getConstantAssignment_3_0(), "rule__IdtFile__ConstantAssignment_3_0");
					put(grammarAccess.getIdtFileAccess().getTypeAssignment_3_1(), "rule__IdtFile__TypeAssignment_3_1");
					put(grammarAccess.getIdtFileAccess().getEndDefAssignment_4(), "rule__IdtFile__EndDefAssignment_4");
					put(grammarAccess.getConstantDefinitionBeginAccess().getNameAssignment_1(), "rule__ConstantDefinitionBegin__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.ow2.mindEd.ui.contentassist.antlr.internal.InternalIdtParser typedParser = (org.ow2.mindEd.ui.contentassist.antlr.internal.InternalIdtParser) parser;
			typedParser.entryRuleIdtFile();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public IdtGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(IdtGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
