/*
 * generated by Xtext
 */
package org.ow2.mindEd.itf.editor.textual.ui.contentassist

import org.ow2.mindEd.itf.editor.textual.ui.contentassist.AbstractFractalItfProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class FractalItfProposalProvider extends AbstractFractalItfProposalProvider {
}
