/*
* generated by Xtext
*/
package org.ow2.mindEd.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.ow2.mindEd.services.AdlGrammarAccess;

public class AdlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AdlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.ow2.mindEd.parser.antlr.internal.InternalAdlParser createParser(XtextTokenStream stream) {
		return new org.ow2.mindEd.parser.antlr.internal.InternalAdlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AdlDefinition";
	}
	
	public AdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
