/*
 * generated by Xtext
 */
package org.ow2.mindEd.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.ow2.mindEd.adl.DataDefinition;
import org.ow2.mindEd.adl.FilePath;
//import org.ow2.mindEd.adl.FileC;
import org.ow2.mindEd.adl.ImplementationDefinition;

/**
 * customization of the default outline structure
 * 
 */
public class AdlOutlineTreeProvider extends DefaultOutlineTreeProvider {

	// SSZ
	// Forcing FileC Outline name, default took only the directory, which is an error.
	protected Object _text(FilePath filePath) {
		return filePath.getName();
	}

	// SSZ
	// Forcing ImplementationDefinition node name as "source" as the element can't be named in the grammar
	protected Object _text(ImplementationDefinition implemDef) {
		return "source";
	}

	// SSZ
	// Forcing ImplementationDefinition node name as "source" as the element can't be named in the grammar
	protected Object _text(DataDefinition dataDef) {
		return "data";
	}

}
