/**
 */
package org.ow2.mindEd.itf.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.ow2.mindEd.itf.util.ItfAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ItfItemProviderAdapterFactory extends ItfAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ItfItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.ItfFile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ItfFileItemProvider itfFileItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.ItfFile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createItfFileAdapter() {
		if (itfFileItemProvider == null) {
			itfFileItemProvider = new ItfFileItemProvider(this);
		}

		return itfFileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.TypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeDefinitionItemProvider typeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.TypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeDefinitionAdapter() {
		if (typeDefinitionItemProvider == null) {
			typeDefinitionItemProvider = new TypeDefinitionItemProvider(this);
		}

		return typeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.TypedefSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypedefSpecificationItemProvider typedefSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.TypedefSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypedefSpecificationAdapter() {
		if (typedefSpecificationItemProvider == null) {
			typedefSpecificationItemProvider = new TypedefSpecificationItemProvider(this);
		}

		return typedefSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.QualifiedTypeSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QualifiedTypeSpecificationItemProvider qualifiedTypeSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.QualifiedTypeSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQualifiedTypeSpecificationAdapter() {
		if (qualifiedTypeSpecificationItemProvider == null) {
			qualifiedTypeSpecificationItemProvider = new QualifiedTypeSpecificationItemProvider(this);
		}

		return qualifiedTypeSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.TypeSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeSpecificationItemProvider typeSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.TypeSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeSpecificationAdapter() {
		if (typeSpecificationItemProvider == null) {
			typeSpecificationItemProvider = new TypeSpecificationItemProvider(this);
		}

		return typeSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.StructOrUnionSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StructOrUnionSpecificationItemProvider structOrUnionSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.StructOrUnionSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStructOrUnionSpecificationAdapter() {
		if (structOrUnionSpecificationItemProvider == null) {
			structOrUnionSpecificationItemProvider = new StructOrUnionSpecificationItemProvider(this);
		}

		return structOrUnionSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.StructOrUnionDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StructOrUnionDefinitionItemProvider structOrUnionDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.StructOrUnionDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStructOrUnionDefinitionAdapter() {
		if (structOrUnionDefinitionItemProvider == null) {
			structOrUnionDefinitionItemProvider = new StructOrUnionDefinitionItemProvider(this);
		}

		return structOrUnionDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.StructorUnionReference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StructorUnionReferenceItemProvider structorUnionReferenceItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.StructorUnionReference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStructorUnionReferenceAdapter() {
		if (structorUnionReferenceItemProvider == null) {
			structorUnionReferenceItemProvider = new StructorUnionReferenceItemProvider(this);
		}

		return structorUnionReferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.StructMember} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StructMemberItemProvider structMemberItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.StructMember}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStructMemberAdapter() {
		if (structMemberItemProvider == null) {
			structMemberItemProvider = new StructMemberItemProvider(this);
		}

		return structMemberItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.EnumSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumSpecificationItemProvider enumSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.EnumSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumSpecificationAdapter() {
		if (enumSpecificationItemProvider == null) {
			enumSpecificationItemProvider = new EnumSpecificationItemProvider(this);
		}

		return enumSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.EnumDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumDefinitionItemProvider enumDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.EnumDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumDefinitionAdapter() {
		if (enumDefinitionItemProvider == null) {
			enumDefinitionItemProvider = new EnumDefinitionItemProvider(this);
		}

		return enumDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.EnumReference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumReferenceItemProvider enumReferenceItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.EnumReference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumReferenceAdapter() {
		if (enumReferenceItemProvider == null) {
			enumReferenceItemProvider = new EnumReferenceItemProvider(this);
		}

		return enumReferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.EnumMemberList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumMemberListItemProvider enumMemberListItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.EnumMemberList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumMemberListAdapter() {
		if (enumMemberListItemProvider == null) {
			enumMemberListItemProvider = new EnumMemberListItemProvider(this);
		}

		return enumMemberListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.EnumMember} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumMemberItemProvider enumMemberItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.EnumMember}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumMemberAdapter() {
		if (enumMemberItemProvider == null) {
			enumMemberItemProvider = new EnumMemberItemProvider(this);
		}

		return enumMemberItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.Declarators} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeclaratorsItemProvider declaratorsItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.Declarators}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeclaratorsAdapter() {
		if (declaratorsItemProvider == null) {
			declaratorsItemProvider = new DeclaratorsItemProvider(this);
		}

		return declaratorsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.Declarator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeclaratorItemProvider declaratorItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.Declarator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeclaratorAdapter() {
		if (declaratorItemProvider == null) {
			declaratorItemProvider = new DeclaratorItemProvider(this);
		}

		return declaratorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.QualifiedPointerSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QualifiedPointerSpecificationItemProvider qualifiedPointerSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.QualifiedPointerSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQualifiedPointerSpecificationAdapter() {
		if (qualifiedPointerSpecificationItemProvider == null) {
			qualifiedPointerSpecificationItemProvider = new QualifiedPointerSpecificationItemProvider(this);
		}

		return qualifiedPointerSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.DirectNamedDeclarator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DirectNamedDeclaratorItemProvider directNamedDeclaratorItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.DirectNamedDeclarator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDirectNamedDeclaratorAdapter() {
		if (directNamedDeclaratorItemProvider == null) {
			directNamedDeclaratorItemProvider = new DirectNamedDeclaratorItemProvider(this);
		}

		return directNamedDeclaratorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.DirectAnonymousDeclarator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DirectAnonymousDeclaratorItemProvider directAnonymousDeclaratorItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.DirectAnonymousDeclarator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDirectAnonymousDeclaratorAdapter() {
		if (directAnonymousDeclaratorItemProvider == null) {
			directAnonymousDeclaratorItemProvider = new DirectAnonymousDeclaratorItemProvider(this);
		}

		return directAnonymousDeclaratorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.ArraySpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArraySpecificationItemProvider arraySpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.ArraySpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArraySpecificationAdapter() {
		if (arraySpecificationItemProvider == null) {
			arraySpecificationItemProvider = new ArraySpecificationItemProvider(this);
		}

		return arraySpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.ConstantDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstantDefinitionItemProvider constantDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.ConstantDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstantDefinitionAdapter() {
		if (constantDefinitionItemProvider == null) {
			constantDefinitionItemProvider = new ConstantDefinitionItemProvider(this);
		}

		return constantDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.InterfaceDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfaceDefinitionItemProvider interfaceDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.InterfaceDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfaceDefinitionAdapter() {
		if (interfaceDefinitionItemProvider == null) {
			interfaceDefinitionItemProvider = new InterfaceDefinitionItemProvider(this);
		}

		return interfaceDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.MethodDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MethodDefinitionItemProvider methodDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.MethodDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMethodDefinitionAdapter() {
		if (methodDefinitionItemProvider == null) {
			methodDefinitionItemProvider = new MethodDefinitionItemProvider(this);
		}

		return methodDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.ParameterList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterListItemProvider parameterListItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.ParameterList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterListAdapter() {
		if (parameterListItemProvider == null) {
			parameterListItemProvider = new ParameterListItemProvider(this);
		}

		return parameterListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.Parameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterItemProvider parameterItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.Parameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterAdapter() {
		if (parameterItemProvider == null) {
			parameterItemProvider = new ParameterItemProvider(this);
		}

		return parameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.IncludeDirective} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IncludeDirectiveItemProvider includeDirectiveItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.IncludeDirective}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIncludeDirectiveAdapter() {
		if (includeDirectiveItemProvider == null) {
			includeDirectiveItemProvider = new IncludeDirectiveItemProvider(this);
		}

		return includeDirectiveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.AnnotationsList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnotationsListItemProvider annotationsListItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.AnnotationsList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnotationsListAdapter() {
		if (annotationsListItemProvider == null) {
			annotationsListItemProvider = new AnnotationsListItemProvider(this);
		}

		return annotationsListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.Annotation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnotationItemProvider annotationItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.Annotation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnotationAdapter() {
		if (annotationItemProvider == null) {
			annotationItemProvider = new AnnotationItemProvider(this);
		}

		return annotationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.AnnotationValuePair} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnotationValuePairItemProvider annotationValuePairItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.AnnotationValuePair}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnotationValuePairAdapter() {
		if (annotationValuePairItemProvider == null) {
			annotationValuePairItemProvider = new AnnotationValuePairItemProvider(this);
		}

		return annotationValuePairItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.AnnotationValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnotationValueItemProvider annotationValueItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.AnnotationValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnotationValueAdapter() {
		if (annotationValueItemProvider == null) {
			annotationValueItemProvider = new AnnotationValueItemProvider(this);
		}

		return annotationValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.ArrayAnnotationValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArrayAnnotationValueItemProvider arrayAnnotationValueItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.ArrayAnnotationValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArrayAnnotationValueAdapter() {
		if (arrayAnnotationValueItemProvider == null) {
			arrayAnnotationValueItemProvider = new ArrayAnnotationValueItemProvider(this);
		}

		return arrayAnnotationValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.ConstantExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstantExpressionItemProvider constantExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.ConstantExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstantExpressionAdapter() {
		if (constantExpressionItemProvider == null) {
			constantExpressionItemProvider = new ConstantExpressionItemProvider(this);
		}

		return constantExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.LogicalOrExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LogicalOrExpressionItemProvider logicalOrExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.LogicalOrExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLogicalOrExpressionAdapter() {
		if (logicalOrExpressionItemProvider == null) {
			logicalOrExpressionItemProvider = new LogicalOrExpressionItemProvider(this);
		}

		return logicalOrExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.LogicalAndExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LogicalAndExpressionItemProvider logicalAndExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.LogicalAndExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLogicalAndExpressionAdapter() {
		if (logicalAndExpressionItemProvider == null) {
			logicalAndExpressionItemProvider = new LogicalAndExpressionItemProvider(this);
		}

		return logicalAndExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.OrExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrExpressionItemProvider orExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.OrExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrExpressionAdapter() {
		if (orExpressionItemProvider == null) {
			orExpressionItemProvider = new OrExpressionItemProvider(this);
		}

		return orExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.XorExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XorExpressionItemProvider xorExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.XorExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXorExpressionAdapter() {
		if (xorExpressionItemProvider == null) {
			xorExpressionItemProvider = new XorExpressionItemProvider(this);
		}

		return xorExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.AndExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AndExpressionItemProvider andExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.AndExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAndExpressionAdapter() {
		if (andExpressionItemProvider == null) {
			andExpressionItemProvider = new AndExpressionItemProvider(this);
		}

		return andExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.ShiftExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ShiftExpressionItemProvider shiftExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.ShiftExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createShiftExpressionAdapter() {
		if (shiftExpressionItemProvider == null) {
			shiftExpressionItemProvider = new ShiftExpressionItemProvider(this);
		}

		return shiftExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.AdditiveExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AdditiveExpressionItemProvider additiveExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.AdditiveExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAdditiveExpressionAdapter() {
		if (additiveExpressionItemProvider == null) {
			additiveExpressionItemProvider = new AdditiveExpressionItemProvider(this);
		}

		return additiveExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.MulExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MulExpressionItemProvider mulExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.MulExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMulExpressionAdapter() {
		if (mulExpressionItemProvider == null) {
			mulExpressionItemProvider = new MulExpressionItemProvider(this);
		}

		return mulExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.CastExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CastExpressionItemProvider castExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.CastExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCastExpressionAdapter() {
		if (castExpressionItemProvider == null) {
			castExpressionItemProvider = new CastExpressionItemProvider(this);
		}

		return castExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.UnaryExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnaryExpressionItemProvider unaryExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.UnaryExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnaryExpressionAdapter() {
		if (unaryExpressionItemProvider == null) {
			unaryExpressionItemProvider = new UnaryExpressionItemProvider(this);
		}

		return unaryExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ow2.mindEd.itf.PrimaryExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimaryExpressionItemProvider primaryExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.ow2.mindEd.itf.PrimaryExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimaryExpressionAdapter() {
		if (primaryExpressionItemProvider == null) {
			primaryExpressionItemProvider = new PrimaryExpressionItemProvider(this);
		}

		return primaryExpressionItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (itfFileItemProvider != null) itfFileItemProvider.dispose();
		if (typeDefinitionItemProvider != null) typeDefinitionItemProvider.dispose();
		if (typedefSpecificationItemProvider != null) typedefSpecificationItemProvider.dispose();
		if (qualifiedTypeSpecificationItemProvider != null) qualifiedTypeSpecificationItemProvider.dispose();
		if (typeSpecificationItemProvider != null) typeSpecificationItemProvider.dispose();
		if (structOrUnionSpecificationItemProvider != null) structOrUnionSpecificationItemProvider.dispose();
		if (structOrUnionDefinitionItemProvider != null) structOrUnionDefinitionItemProvider.dispose();
		if (structorUnionReferenceItemProvider != null) structorUnionReferenceItemProvider.dispose();
		if (structMemberItemProvider != null) structMemberItemProvider.dispose();
		if (enumSpecificationItemProvider != null) enumSpecificationItemProvider.dispose();
		if (enumDefinitionItemProvider != null) enumDefinitionItemProvider.dispose();
		if (enumReferenceItemProvider != null) enumReferenceItemProvider.dispose();
		if (enumMemberListItemProvider != null) enumMemberListItemProvider.dispose();
		if (enumMemberItemProvider != null) enumMemberItemProvider.dispose();
		if (declaratorsItemProvider != null) declaratorsItemProvider.dispose();
		if (declaratorItemProvider != null) declaratorItemProvider.dispose();
		if (qualifiedPointerSpecificationItemProvider != null) qualifiedPointerSpecificationItemProvider.dispose();
		if (directNamedDeclaratorItemProvider != null) directNamedDeclaratorItemProvider.dispose();
		if (directAnonymousDeclaratorItemProvider != null) directAnonymousDeclaratorItemProvider.dispose();
		if (arraySpecificationItemProvider != null) arraySpecificationItemProvider.dispose();
		if (constantDefinitionItemProvider != null) constantDefinitionItemProvider.dispose();
		if (interfaceDefinitionItemProvider != null) interfaceDefinitionItemProvider.dispose();
		if (methodDefinitionItemProvider != null) methodDefinitionItemProvider.dispose();
		if (parameterListItemProvider != null) parameterListItemProvider.dispose();
		if (parameterItemProvider != null) parameterItemProvider.dispose();
		if (includeDirectiveItemProvider != null) includeDirectiveItemProvider.dispose();
		if (annotationsListItemProvider != null) annotationsListItemProvider.dispose();
		if (annotationItemProvider != null) annotationItemProvider.dispose();
		if (annotationValuePairItemProvider != null) annotationValuePairItemProvider.dispose();
		if (annotationValueItemProvider != null) annotationValueItemProvider.dispose();
		if (arrayAnnotationValueItemProvider != null) arrayAnnotationValueItemProvider.dispose();
		if (constantExpressionItemProvider != null) constantExpressionItemProvider.dispose();
		if (logicalOrExpressionItemProvider != null) logicalOrExpressionItemProvider.dispose();
		if (logicalAndExpressionItemProvider != null) logicalAndExpressionItemProvider.dispose();
		if (orExpressionItemProvider != null) orExpressionItemProvider.dispose();
		if (xorExpressionItemProvider != null) xorExpressionItemProvider.dispose();
		if (andExpressionItemProvider != null) andExpressionItemProvider.dispose();
		if (shiftExpressionItemProvider != null) shiftExpressionItemProvider.dispose();
		if (additiveExpressionItemProvider != null) additiveExpressionItemProvider.dispose();
		if (mulExpressionItemProvider != null) mulExpressionItemProvider.dispose();
		if (castExpressionItemProvider != null) castExpressionItemProvider.dispose();
		if (unaryExpressionItemProvider != null) unaryExpressionItemProvider.dispose();
		if (primaryExpressionItemProvider != null) primaryExpressionItemProvider.dispose();
	}

}
