/*
 * generated by Xtext
 */
package org.ow2.mindEd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class IdtUiModule extends org.ow2.mindEd.ui.AbstractIdtUiModule {
	public IdtUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
